query GetMediaDetails($id: Int) {
  Media(id: $id) {
    id
    title {
      romaji
      english
    }
    description
    coverImage {
      extraLarge
    }
    bannerImage
    averageScore
    popularity
    status
    format
    episodes
    chapters
    genres
    season
    seasonYear
    characters(role: MAIN, sort: [ROLE]) {
      nodes {
        id
        name {
          full
        }
        image {
          large
        }
      }
    }
    recommendations(perPage: 10, sort: [RATING_DESC]) {
      nodes {
        mediaRecommendation {
          id
          title {
            romaji
            english
          }
          coverImage {
            large
          }
        }
      }
    }
  }
}
