query SearchMedia($search: String, $type: MediaType, $page: Int) {
  Page(page: $page, perPage: 20) {
    media(search: $search, type: $type) {
      id
      title {
        romaji
        english
      }
      description
      coverImage {
        extraLarge
      }
      bannerImage
      averageScore
      popularity
      status
      format
      episodes
      chapters
      trailer {
        id
        site
      }
      genres
      season
      seasonYear
    }
    characters(search: $search) {
      id
      name {
        full
      }
      image {
        large
      }
      description
    }
  }
}
